services:
  mongo:
    image: mongo:7
    container_name: comp3095-mongodb
    ports:
      - "27017:27017"
    networks: [mynetwork]

  mongo-express:
    image: mongo-express:1.0.2
    depends_on: [mongo]
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH=false
    networks: [mynetwork]

  product-service:
    build:
      context: ./product-service
    image: comp3095/product-service:latest
    depends_on: [mongo]
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/product-service
      - SERVER_PORT=8084
    ports:
      - "8084:8084"
    networks: [mynetwork]

networks:
  mynetwork:
    driver: bridge
